services:
  sullerk-client:
    image: euhandev/navelle-frontend:latest
    container_name: navelle-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped